name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Check for package-lock.json in subdirectories and install dependencies
        run: |
          for dir in */; do
            if [ -f "$dir/package-lock.json" ]; then
              echo "Found package-lock.json in $dir, running npm ci"
              cd "$dir"
              npm ci
              cd ..
            else
              echo "No package-lock.json in $dir, skipping npm ci"
            fi
          done
      
      # 如果 package.json 在 backend 文件夹
      - name: Run tests
        working-directory: ./backend  # 指定包含 package.json 的目录
        run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          
      - name: Check for package-lock.json in subdirectories and install dependencies
        run: |
          for dir in */; do
            if [ -f "$dir/package-lock.json" ]; then
              echo "Found package-lock.json in $dir, running npm ci"
              cd "$dir"
              npm ci
              cd ..
            else
              echo "No package-lock.json in $dir, skipping npm ci"
            fi
          done
      
      # 如果 package.json 在 backend 文件夹
      - name: Publish package
        working-directory: ./backend  # 指定包含 package.json 的目录
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
